#!/bin/sh
REPO=$1
BUILD_FILE="$HOME/.huh/build/BUILD.box"

log_error() {
  printf "\033[38;5;196m░▒▓\033[48;5;196;38;5;196m█\033[48;5;196;37;1m error: %s \033[48;5;196;38;5;196m█\033[0m\033[38;5;196m▓▒░\033[0m\n" "$1"
}

git clone -q "https://github.com/$REPO" "$HOME/.huh/build/" > /dev/null 2>&1

if [ ! -f "$BUILD_FILE" ]; then
  log_error "BUILD.box not found in repository."
  rm -rf ~/.huh/build
  exit 1
fi

cd "$HOME/.huh/build/" || exit 1

while IFS= read -r line || [ -n "$line" ]; do
  [ -z "$line" ] && continue
  case "$line" in \#*) continue ;; esac

  eval "$line"
done < "$BUILD_FILE"

if [ ! -d "./PKGINSTALL" ]; then
  log_error "PKGINSTALL directory not found"
  rm -rf ~/.huh/build
  exit 1
fi

mv ./PKGINSTALL/* ~/.huh/
rm -rf ~/.huh/build
